### ISSUE TITLE
Add to component wiki?

### ISSUE THREAD

**Issue by timoxley** [enyo/domready#1]
https://github.com/component/component/wiki/Components

**Comment by enyo** [comment]
Yeah I think that would be good for now. Although I didn't write the
code but took it from an ender module. (I'm not that happy with the
code style but it works!)

When I have the time I'll work on it but there's no harm in adding it
right away.

**Comment by kenany** [comment]
Just found this through the wiki so I believe we're done here :grin:

**Comment by timoxley** [comment]
:+1: :+1:
